model:
  antialias: 0
  arch: "resnet18" 
resolution:
  min_res: 160
  max_res: 160
  end_ramp: 0
data:
  num_workers: 10
  gpu: 0
  train_dataset: "/dev/shm/imgnet_train_250px.beton"
  val_dataset: "/dev/shm/imgnet_val_250px.beton"
logging:
  folder: "logs/"
training:
  batch_size: 512
  optimizer: "sgd"
  lr: 0.2
  momentum: 0.9
  weight_decay: 4e-5
  epochs: 90
  label_smoothing: 0.1
  lr_peak_epoch: 5
validation:
  batch_size: 1024
  resolution: 224
  lr_tta: 1