model:
  antialias: true
  # arch: TODO 
resolution:
  min_res: 64
  max_res: 160
  end_ramp: 12
data:
  workers: 11
  gpu: 0
training:
  batch_size: 512
  optimizer: "sgd"
  lr: 0.2
  momentum: 0.9
  weight_decay: 1e-4
  epochs: 90 # TODO: add step learning rate
  label_smoothing: 0
  lr_peak_epoch: 5 # TODO: remove on step learning rate
validation:
  batch_size: 1024
  crop_size: 224
  resolution: 224
  lr_tta: False