model:
  antialias: false
  arch: 'resnet18'
resolution:
  min_res: 224
  max_res: 224
  end_ramp: 0
data:
  gpu: 0
  train_dataset: '/mnt/cfs/home/engstrom/store/ffcv/train_150.ffcv'
  val_dataset: '/mnt/cfs/home/engstrom/store/ffcv/val_150.ffcv'
  num_workers: 11
logging:
  folder: '/tmp/'
training:
  batch_size: 1024
  optimizer: "sgd"
  lr: 0.8
  momentum: 0.9
  weight_decay: 5e-4
  epochs: 89
  label_smoothing: 0
  lr_schedule_type: 'step'
  step_ratio: 0.1
  step_length: 30
validation:
  batch_size: 1024
  resolution: 288
  lr_tta: False