model:
  antialias: false
  # arch: TODO
resolution:
  min_res: 224
  max_res: 224
  end_ramp: 0
data:
  gpu: 0
training:
  batch_size: 512
  optimizer: "sgd"
  lr: 0.2
  momentum: 0.9
  weight_decay: 1e-4
  epochs: 90 # TODO: add step learning rate
  label_smoothing: 0
  lr_peak_epoch: 5 # TODO: remove on step learning rate
validation:
  batch_size: 1024
  crop_size: 224
  resolution: 224
  lr_tta: False